### ISSUE TITLE
Bug: RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.

### ISSUE THREAD

**Issue by nounouthereal** [Maxisthemoose/discord-uno#11]
Hi I have this error is there a way to fix it :
 `RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.
    at Function.verifyString (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/util/Util.js:428:49)
    at MessagePayload.makeContent (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/structures/MessagePayload.js:114:22)
    at MessagePayload.resolveData (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/structures/MessagePayload.js:129:26)
    at TextChannel.send (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:61)
    at DiscordUNO.createGame (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord-uno/lib/index.js:85:32)
    at Object.module.exports.run (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/commands/games/uno.js:42:30)
    at module.exports (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/events/messageCreate.js:80:31)
    at MongoClient.emit (node:events:527:28)
    at MessageCreateAction.handle (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
    at Object.module.exports [as MESSAGE_CREATE] (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:478:22)
    at WebSocketShard.onMessage (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
    at WebSocket.onMessage (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/ws/lib/websocket.js:1169:20) {
  [Symbol(code)]: 'MESSAGE_CONTENT_TYPE'
} Promise {
  <rejected> RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.
      at Function.verifyString (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/util/Util.js:428:49)
      at MessagePayload.makeContent (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/structures/MessagePayload.js:114:22)
      at MessagePayload.resolveData (/Users/v/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/structures/MessagePayload.js:129:26)
      at TextChannel.send (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:172:61)
      at DiscordUNO.createGame (/Users/v/Bot_des_cerisiers/Js/bot/node_modules/discord-uno/lib/index.js:85:32)
      at Object.module.exports.run (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/commands/games/uno.js:42:30)
      at module.exports (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/events/messageCreate.js:80:31)
      at MongoClient.emit (node:events:527:28)
      at MessageCreateAction.handle (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/actions/MessageCreate.js:26:14)
      at Object.module.exports [as MESSAGE_CREATE] (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
      at WebSocketManager.handlePacket (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
      at WebSocketShard.onPacket (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:478:22)
      at WebSocketShard.onMessage (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:317:10)
      at WebSocket.onMessage (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/ws/lib/event-target.js:199:18)
      at WebSocket.emit (node:events:527:28)
      at Receiver.receiverOnMessage (/Users/HIDDEN/Bot_des_cerisiers/Js/bot/node_modules/ws/lib/websocket.js:1169:20) {
    [Symbol(code)]: 'MESSAGE_CONTENT_TYPE'
  }
}`

**Comment by seasaltsaige** [comment]
Discord UNO hasn't been updated in 2 years. If you want to try update the package itself to whatever point discord.js is at, feel free to do that, but I'm not maintaining this package really anymore

**Comment by nounouthereal** [comment]
ok...
